language: ruby
rvm:
  - 2.6
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

script: JEKYLL_ENV=production bundle exec jekyll build

before_deploy: echo "lucasvienna.dev" > _site/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
