language: ruby
rvm:
  - 2.6
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

script: bundle exec jekyll build

after_script: cp -r _site/ docs/

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
